// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXgt51eZGqWQnsrwWYgyy6hYP2Ojt_G2A',
    appId: '1:582334193763:web:1b3905f964cd80ea8ed856',
    messagingSenderId: '582334193763',
    projectId: 'kawaii-gallery',
    authDomain: 'kawaii-gallery.firebaseapp.com',
    storageBucket: 'kawaii-gallery.appspot.com',
    measurementId: 'G-DBHJFMYTGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9mS_Xc5L1y3XIM9eSJK8odwjv0CrP_8w',
    appId: '1:582334193763:android:4b2d7aa0a1180d6c8ed856',
    messagingSenderId: '582334193763',
    projectId: 'kawaii-gallery',
    storageBucket: 'kawaii-gallery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAji7WwbW96jiLN8oMfL9KAmpD1T8B6JJ8',
    appId: '1:582334193763:ios:4ebd606d1c6eaffa8ed856',
    messagingSenderId: '582334193763',
    projectId: 'kawaii-gallery',
    storageBucket: 'kawaii-gallery.appspot.com',
    iosBundleId: 'com.example.todayCute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAji7WwbW96jiLN8oMfL9KAmpD1T8B6JJ8',
    appId: '1:582334193763:ios:4ebd606d1c6eaffa8ed856',
    messagingSenderId: '582334193763',
    projectId: 'kawaii-gallery',
    storageBucket: 'kawaii-gallery.appspot.com',
    iosBundleId: 'com.example.todayCute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXgt51eZGqWQnsrwWYgyy6hYP2Ojt_G2A',
    appId: '1:582334193763:web:ed51dff2f59f08c98ed856',
    messagingSenderId: '582334193763',
    projectId: 'kawaii-gallery',
    authDomain: 'kawaii-gallery.firebaseapp.com',
    storageBucket: 'kawaii-gallery.appspot.com',
    measurementId: 'G-1PSV14VHL6',
  );
}
